version: '3'

services:
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kahrol52
      POSTGRES_DB: astrodb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
  node:
    build: .
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      DATABASE_URL: postgres://postgres:kahrol52@postgres:5432/astrodb
      SECRET_KEY: "Essa-dev-aqui-eh-zika"
      
    command: sh -c "npx prisma migrate deploy" 
volumes:
  postgres_data: